repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: flake8
        args: [--config=setup.cfg]
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-merge-conflict
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.1.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.711
    hooks:
    -   id: mypy
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-n, '10', -s, B101]
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.19.0
    hooks:
    -   id: pyupgrade
