repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: flake8
        args: [--config=setup.cfg]
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.641
    hooks:
    -   id: mypy
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-n, '10', -s, B101]