repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: [--config=tox.ini]
        additional_dependencies: [flake8-isort==2.7.0, flake8-typing-imports==1.5.0, flake8-bugbear==19.8.0]
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.750
    hooks:
    -   id: mypy
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-n, '10', '--ini', 'tox.ini']
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.25.1
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-merge-conflict
