language: python
dist: xenial
cache: pip
stages:
  - lint
  - test
python:
  - 3.5-dev
  - 3.6-dev
  - 3.7-dev
  - 3.8-dev
matrix:
  include:
    - python: 3.5-dev
    - env: EVENT_LOOP=asyncio TOXENV=clean,py35-asyncio,coverage
    - python: 3.5-dev
    - env: EVENT_LOOP=uvloop TOXENV=clean,py35-uvloop,coverage
    - python: 3.6-dev
    - env: EVENT_LOOP=asyncio TOXENV=clean,py36-asyncio,coverage
    - python: 3.6-dev
    - env: EVENT_LOOP=uvloop TOXENV=clean,py36-uvloop,coverage
    - python: 3.7-dev
    - env: EVENT_LOOP=asyncio TOXENV=clean,py37-asyncio,coverage
    - python: 3.7-dev
    - env: EVENT_LOOP=uvloop TOXENV=clean,py37-uvloop,coverage
    - python: 3.8-dev
    - env: EVENT_LOOP=asyncio TOXENV=clean,py38-asyncio,coverage
    - python: 3.8-dev
    - env: EVENT_LOOP=uvloop TOXENV=clean,py38-uvloop,coverage
  allow_failures:
    - python: 3.5-dev
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
script: tox
install:
  - 'pip install tox-travis pytest-travis-fold coveralls'
after_success:
  - 'COVERALLS_PARALLEL=true coveralls'
notifications:
  webhooks: 'https://coveralls.io/webhook'
jobs:
  include:
    - stage: lint
      name: 'Lint'
      install: 'pip install tox'
      after_success: skip
      python: '3.7'
      env: EVENT_LOOP=asyncio TOXENV=check,mypy,flake8,black,bandit,docs
      script: tox
