language: python
dist: xenial
cache: pip
stages:
  - lint
  - test
  - name: release
    if: tag IS present
python:
  - 3.5.2
  - '3.5'
  - '3.6'
  - '3.7'
  - pypy3.5
  - 3.5-dev
  - 3.6-dev
  - 3.7-dev
  - 3.8-dev
env:
  - EVENT_LOOP=asyncio
  - EVENT_LOOP=uvloop
matrix:
  exclude:
    - python: pypy3.5
      env: EVENT_LOOP=uvloop
  fast_finish: true
  allow_failures:
    - python: pypy3.5
    - python: 3.5-dev
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
script: tox
install:
  - 'pip install tox-travis pytest-travis-fold coveralls codecov'
after_success:
  - 'COVERALLS_PARALLEL=true coveralls'
  - codecov
notifications:
  webhooks: 'https://coveralls.io/webhook'
jobs:
  include:
    - stage: lint
      name: 'setup.py check'
      install: 'pip install tox'
      after_success: skip
      python: '3.6'
      env: EVENT_LOOP=asyncio
      script: 'tox -e check'
    - script: 'tox -e mypy'
      name: 'mypy'
      install: 'pip install tox'
      after_success: skip
      python: '3.6'
      env: EVENT_LOOP=asyncio
    - script: 'tox -e flake8'
      name: 'flake8'
      install: 'pip install tox'
      after_success: skip
      python: '3.6'
      env: EVENT_LOOP=asyncio
    - script: 'tox -e black'
      name: 'black'
      install: 'pip install tox'
      after_success: skip
      python: '3.6'
      env: EVENT_LOOP=asyncio
    - script: 'tox -e bandit'
      name: 'bandit'
      install: 'pip install tox'
      after_success: skip
      python: '3.6'
      env: EVENT_LOOP=asyncio
    - script: 'tox -e docs'
      name: 'sphinx build & doctests'
      install: 'pip install tox'
      after_success: skip
      python: '3.6'
      env: EVENT_LOOP=asyncio
    - stage: release
      name: 'Release to PyPi'
      script: skip
      install: skip
      python: '3.6'
      env: EVENT_LOOP=asyncio
      deploy:
        provider: pypi
        user: colemaclean
        password:
          secure: bJ8T2v/YZlQU7iLmoJmrWZ0H51GtbhOw6AWtVErMQ2HF4HDRIcGhQXmxKmxG7Hs3mUbe7l7NWtJCtZzHKC1I5N0UZYlioFpC6yFYkqQDNoau9D203C7zdlXA47OezvzDmB/Kt1LQ3D/xd7Ji9hQHKwwVMC76IAhwZxl8Y5UBX6M=
        distributions: 'sdist bdist_wheel'
        on:
          tags: true
          repo: cole/aiosmtplib
