language: python
dist: xenial
cache: pip
python:
  - 3.5-dev
  - 3.6-dev
  - 3.7-dev
  - 3.8-dev
matrix:
  allow_failures:
    - python: 3.5-dev
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
script: tox
install:
  - 'pip install tox-travis pytest-travis-fold coveralls'
after_success:
  - 'COVERALLS_PARALLEL=true coveralls'
notifications:
  webhooks: 'https://coveralls.io/webhook'
