variables:
  CI: 'true'

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python352:
        python.version: '3.5.2'
        toxenv: 'py35-asyncio'
      Python35:
        python.version: '3.5'
        toxenv: 'py35-asyncio'
      Python36:
        python.version: '3.6'
        toxenv: 'py36-asyncio'
      Python37:
        python.version: '3.7'
        toxenv: 'py37-asyncio'
      Python352-UVLoop:
        python.version: '3.5.2'
        toxenv: 'py35-uvloop'
      Python35-UVLoop:
        python.version: '3.5'
        toxenv: 'py35-uvloop'
      Python36-UVLoop:
        python.version: '3.6'
        toxenv: 'py36-uvloop'
      Python37-UVLoop:
        python.version: '3.7'
        toxenv: 'py37-uvloop'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install tox tox-venv
    displayName: 'Install Tox'

  - script: tox -e $(toxenv)
    displayName: 'Run Tox'
