variables:
  CI: 'true'

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        containerImage: ubuntu:16.04
        python.version: '3.5'
        tox.env: 'clean,py35-asyncio,py35-uvloop,coverage'
      Python36:
        containerImage: ubuntu:16.04
        python.version: '3.6'
        tox.env: 'clean,py36-asyncio,py36-uvloop,coverage'
      Python37:
        containerImage: ubuntu:16.04
        python.version: '3.7'
        tox.env: 'clean,py37-asyncio,py37-uvloop,coverage'
      PyPy35:
        containerImage: ubuntu:16.04
        python.version: 'pypy3'
        tox.env: 'clean,pypy35-asyncio,coverage'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python 3.7 for tox'
    inputs:
      versionSpec: '3.7'
      addToPath: false
    name: toxPython
  - script: $(toxPython.pythonLocation)/bin/pip install --upgrade pip
    displayName: 'Upgrade pip'
  - script: $(toxPython.pythonLocation)/bin/pip install --upgrade tox tox-venv
    displayName: 'Install tox'
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version) for tests'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: tox -e $(tox.env)
    displayName: 'Run Tox (env: $(tox.env))'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results/**/results.xml'
      testRunTitle: '$(python.version) Test Run'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      failIfCoverageEmpty: true
