variables:
  CI: 'true'
  EVENT_LOOP: 'asyncio'

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python352:
        python.version: '3.5.2'
        TOXENV: 'clean,py35-asyncio,coverage'
      Python35:
        python.version: '3.5'
        TOXENV: 'clean,py35-asyncio,coverage'
      Python36:
        python.version: '3.6'
        TOXENV: 'clean,py36-asyncio,coverage'
      Python37:
        python.version: '3.7'
        TOXENV: 'clean,py37-asyncio,coverage'
      Python352-UVLoop:
        python.version: '3.5.2'
        TOXENV: 'clean,py35-uvloop,coverage'
        EVENT_LOOP: 'uvloop'
      Python35-UVLoop:
        python.version: '3.5'
        TOXENV: 'clean,py35-uvloop,coverage'
        EVENT_LOOP: 'uvloop'
      Python36-UVLoop:
        python.version: '3.6'
        TOXENV: 'clean,py36-uvloop,coverage'
        EVENT_LOOP: 'uvloop'
      Python37-UVLoop:
        python.version: '3.7'
        TOXENV: 'clean,py37-uvloop,coverage'
        EVENT_LOOP: 'uvloop'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
    # Ubuntu 16.04 default Python is 3.5.2
    condition: ne(variables['python.version'], '3.5.2')
  - script: pip install --upgrade pip
    displayName: 'Upgrade pip'
  - script: pip install tox tox-venv
    displayName: 'Install Tox'
  - script: tox
    displayName: 'Run Tox'
