variables:
  CI: 'true'

trigger:
- master

resources:
  containers:
  - container: py352
    image: python:3.5.2
  - container: py35
    image: python:3.5
  - container: py36
    image: python:3.6
  - container: py37
    image: python:3.7
  - container: py38
    image: python:3.8-rc

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  strategy:
    matrix:
      Python352:
        containerName: py352
        toxEnv: 'py35-asyncio'
      Python35:
        containerName: py35
        toxEnv: 'py35-asyncio'
      Python36:
        containerName: py36
        toxEnv: 'py36-asyncio'
      Python37:
        containerName: py37
        toxEnv: 'py37-asyncio'
      Python352-UVLoop:
        containerName: py352
        toxenv: 'py35-uvloop'
      Python35-UVLoop:
        containerName: py35
        toxEnv: 'py35-uvloop'
      Python36-UVLoop:
        containerName: py36
        toxEnv: 'py36-uvloop'
      Python37-UVLoop:
        containerName: py37
        toxEnv: 'py37-uvloop'

  container: '$(containerName)'

  steps:

  - script: pip install tox tox-venv
    displayName: 'Install Tox'

  - script: tox -e $(toxEnv)
    displayName: 'Run Tox'
