version: 2.1

commands:
  install_tox:
    description: "Install tox"
    steps:
      - restore_cache:
          keys:
            - v2-pip
      - run:
          command: mkdir -p ~/pip-cache
          name: "Create pip cache dir"
      - run:
          command: pip --cache-dir ~/pip-cache install tox tox-venv
          name: "Install tox & tox-venv"
      - save_cache:
          paths:
            - ~/pip-cache
          key: v2-pip

  install_tox_deps:
    description: "Install tox dependencies"
    parameters:
      toxenvs:
        type: string
        default: "ALL"
    steps:
      - restore_cache:
          keys:
            - v3-tox-<< parameters.toxenvs >>-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
            - v3-tox-<< parameters.toxenvs >>-{{ .Branch }}-
            - v3-tox-<< parameters.toxenvs >>-
      - run:
          command: mkdir -p ~/tox-workdir
          name: "Create tox work dir"
      - run:
          command: tox --workdir ~/tox-workdir --notest -e << parameters.toxenvs >>
          name: "Install tox env dependencies: << parameters.toxenvs >>"
      - save_cache:
          paths:
            - ~/tox-workdir
          key: v3-tox-<< parameters.toxenvs >>-{{ .Branch }}-{{ checksum "requirements-test.txt" }}

  run_tox:
    description: "Run tox"
    parameters:
      toxenv:
        type: string
        default: "ALL"
    steps:
      - run:
          command: tox --workdir ~/tox-workdir -e << parameters.toxenv >>
          name: "Tox: << parameters.toxenv >>"

jobs:

  lint:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: check,mypy,flake8,black,bandit
      - run_tox:
          toxenv: check
      - run_tox:
          toxenv: mypy
      - run_tox:
          toxenv: flake8
      - run_tox:
          toxenv: black
      - run_tox:
          toxenv: bandit

  py352-asyncio:
    docker:
      - image: python:3.5.2
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,py35-asyncio,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: py35-asyncio
      - run_tox:
          toxenv: coverage

  py352-uvloop:
    docker:
      - image: python:3.5.2
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,py35-uvloop,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: py35-uvloop
      - run_tox:
          toxenv: coverage

  py35-asyncio:
    docker:
      - image: python:3.5-stretch
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,py35-asyncio,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: py35-asyncio
      - run_tox:
          toxenv: coverage

  py35-uvloop:
    docker:
      - image: python:3.5-stretch
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,py35-uvloop,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: py35-uvloop
      - run_tox:
          toxenv: coverage

  py36-asyncio:
    docker:
      - image: python:3.6-stretch
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,py36-asyncio,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: py36-asyncio
      - run_tox:
          toxenv: coverage

  py36-uvloop:
    docker:
      - image: python:3.6-stretch
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,py36-uvloop,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: py36-uvloop
      - run_tox:
          toxenv: coverage

  py37-asyncio:
    docker:
      - image: python:3.7-stretch
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,py37-asyncio,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: py37-asyncio
      - run_tox:
          toxenv: coverage

  py37-uvloop:
    docker:
      - image: python:3.7-stretch
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,py37-uvloop,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: py37-uvloop
      - run_tox:
          toxenv: coverage

  pypy35-asyncio:
    docker:
      - image: pypy:3.5-stretch
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,pypy35-asyncio,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: pypy35-asyncio
      - run_tox:
          toxenv: coverage

  pypy36-asyncio:
    docker:
      - image: pypy:3.6-stretch
    steps:
      - checkout
      - install_tox
      - install_tox_deps:
          toxenvs: clean,pypy36-asyncio,coverage
      - run_tox:
          toxenv: clean
      - run_tox:
          toxenv: pypy36-asyncio
      - run_tox:
          toxenv: coverage

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - py352-asyncio:
          requires:
            - lint
      - py35-asyncio:
          requires:
            - lint
      - py36-asyncio:
          requires:
            - lint
      - py37-asyncio:
          requires:
            - lint
      - py352-uvloop:
          requires:
            - lint
      - py35-uvloop:
          requires:
            - lint
      - py36-uvloop:
          requires:
            - lint
      - py37-uvloop:
          requires:
            - lint
      - pypy35-asyncio:
          requires:
            - lint
      - pypy36-asyncio:
          requires:
            - lint
