version: 2.1

commands:
  install_tox:
    description: "Install tox"
    steps:
      - restore_cache:
          keys:
            - v2-pip
          name: "Restoring pip cache"
      - run:
          command: mkdir -p ~/pip-cache
          name: "Creating pip cache dir"
      - run:
          command: pip --cache-dir ~/pip-cache install tox tox-venv
          name: "Installing tox & tox-venv"
      - save_cache:
          paths:
            - ~/pip-cache
          key: v2-pip
          name: "Saving pip cache"

  cache_tox_workdir:
    description: "Cache tox workdir"
    parameters:
      cache_key:
        type: string
      tox_runs:
        type: steps
        default: []
    steps:
      - restore_cache:
          keys:
            - v4-tox-<< parameters.cache_key >>-{{ checksum "requirements-test.txt" }}-{{ .Branch }}
            - v4-tox-<< parameters.cache_key >>-{{ checksum "requirements-test.txt" }}-
          name: "Restoring tox envs cache: << parameters.cache_key >>"
      - run:
          command: mkdir -p ~/tox-workdir
          name: "Creating tox work dir"
      - steps: << parameters.tox_runs >>
      - save_cache:
          paths:
            - ~/tox-workdir
          key: v4-tox-<< parameters.cache_key >>-{{ checksum "requirements-test.txt" }}-{{ .Branch }}
          name: "Saving tox workdir cache: << parameters.cache_key >>"

  run_tox:
    description: "Run tox"
    parameters:
      toxenv:
        type: string
        default: "ALL"
    steps:
      - run:
          command: tox --workdir ~/tox-workdir -e << parameters.toxenv >>
          name: "Running tox: << parameters.toxenv >>"

  install_and_run_toxenvs:
    description: "Install and run tox with multiple envs"
    parameters:
      toxenvs:
        type: string
        default: "ALL"
    steps:
      - install_tox
      - cache_tox_workdir:
          cache_key: << parameters.toxenvs >>
          tox_runs:
            - run_tox:
                toxenv: << parameters.toxenvs >>
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: coverage.xml
      - store_artifacts:
          path: htmlcov

jobs:

  lint:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - install_tox
      - cache_tox_workdir:
          cache_key: check,mypy,flake8,black,bandit
          tox_runs:
            - run_tox:
                toxenv: check
            - run_tox:
                toxenv: mypy
            - run_tox:
                toxenv: flake8
            - run_tox:
                toxenv: black
            - run_tox:
                toxenv: bandit

  py352:
    docker:
      - image: python:3.5.2
    steps:
      - checkout
      - install_and_run_toxenvs:
          toxenvs: clean,py35-asyncio,py35-uvloop,coverage

  py35:
    docker:
      - image: python:3.5-stretch
    steps:
      - checkout
      - install_and_run_toxenvs:
          toxenvs: clean,py35-asyncio,py35-uvloop,coverage

  py36:
    docker:
      - image: python:3.6-stretch
    steps:
      - checkout
      - install_and_run_toxenvs:
          toxenvs: clean,py36-asyncio,py36-uvloop,coverage

  py37:
    docker:
      - image: python:3.7-stretch
    steps:
      - checkout
      - install_and_run_toxenvs:
          toxenvs: clean,py37-asyncio,py37-uvloop,coverage

  pypy35:
    docker:
      - image: pypy:3.5-stretch
    steps:
      - checkout
      - install_and_run_toxenvs:
          toxenvs: clean,pypy35-asyncio,coverage

  pypy36:
    docker:
      - image: pypy:3.6-stretch
    steps:
      - checkout
      - install_and_run_toxenvs:
          toxenvs: clean,pypy36-asyncio,coverage

  py38:
    docker:
      - image: python:3.8-rc-buster
    steps:
      - checkout
      # uvloop on py38 is broken :(
      - install_and_run_toxenvs:
          toxenvs: clean,py38-asyncio,coverage

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - py352:
          requires:
            - lint
      - py35:
          requires:
            - lint
      - py36:
          requires:
            - lint
      - py37:
          requires:
            - lint
      - pypy35:
          requires:
            - lint
      - pypy36:
          requires:
            - lint
      - py38:
          requires:
            - lint
