version: 2.1

commands:
  install_tox:
    description: "pip install tox"
    steps:
      - restore_cache:
          keys:
            - v1-pip
      - run: mkdir -p /deps/pip
      - run: pip --cache-dir /deps/pip install tox tox-venv
      - save_cache:
          paths:
            - /deps/pip
          key: v1-pip

  run_tox:
    description: "tox"
    steps:
      - restore_cache:
          keys:
            - v1-tox-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
            - v1-tox-{{ .Branch }}-
            - v1-tox-
      - run: mkdir -p /deps/tox
      - run: tox --workdir /deps/tox --notest
      - save_cache:
          paths:
            - /deps/tox
          key: v1-tox-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
      - run: tox --workdir /deps/tox

jobs:

  lint:
    docker:
      - image: python:3.7
    environment:
      TOXENV: check,mypy,flake8,black,bandit
    steps:
      - checkout
      - install_tox
      - run_tox

  py352-asyncio:
    docker:
      - image: python:3.5.2
    environment:
      TOXENV: clean,py35-asyncio,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  py352-uvloop:
    docker:
      - image: python:3.5.2
    environment:
      TOXENV: clean,py35-uvloop,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  py35-asyncio:
    docker:
      - image: python:3.5-stretch
    environment:
      TOXENV: clean,py35-asyncio,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  py35-uvloop:
    docker:
      - image: python:3.5-stretch
    environment:
      TOXENV: clean,py35-uvloop,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  py36-asyncio:
    docker:
      - image: python:3.6-stretch
    environment:
      TOXENV: clean,py36-asyncio,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  py36-uvloop:
    docker:
      - image: python:3.6-stretch
    environment:
      TOXENV: clean,py36-uvloop,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  py37-asyncio:
    docker:
      - image: python:3.7-stretch
    environment:
      TOXENV: clean,py37-asyncio,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  py37-uvloop:
    docker:
      - image: python:3.7-stretch
    environment:
      TOXENV: clean,py37-uvloop,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  pypy35-asyncio:
    docker:
      - image: pypy:3.5-stretch
    environment:
      TOXENV: clean,pypy35-asyncio,coverage
    steps:
      - checkout
      - install_tox
      - run_tox

  pypy36-asyncio:
    docker:
      - image: pypy:3.6-stretch
    environment:
      TOXENV: clean,pypy36-asyncio,coverage
    steps:
      - checkout
      - install_tox
      - run_tox


workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - py352-asyncio:
          requires:
            - lint
      - py35-asyncio:
          requires:
            - lint
      - py36-asyncio:
          requires:
            - lint
      - py37-asyncio:
          requires:
            - lint
      - py352-uvloop:
          requires:
            - lint
      - py35-uvloop:
          requires:
            - lint
      - py36-uvloop:
          requires:
            - lint
      - py37-uvloop:
          requires:
            - lint
      - pypy35-asyncio:
          requires:
            - lint
      - pypy36-asyncio:
          requires:
            - lint
